name: capital
description: Isurance brokerage application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  splashscreen: ^1.3.5
  bottom_navy_bar: ^6.0.0
  persistent_bottom_nav_bar: ^4.0.2
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  geolocator: ^5.1.5
  mailer: ^3.3.0
  http: ^0.12.2
  custom_navigator: ^0.3.0
  provider: ^5.0.0
  email_validator: ^2.0.1
  image_picker: any
  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
     - images/


